Fix quickstart.sh workflow (#418)
* Fix quickstart.sh workflow

* Don't await tail PID, busy wait instead

* Use ripgrep instead

* Run on pushes and PRs targeting master

* Run tail in subshell

* Use grep -q instead of grep -m1

* Catch SIGPIPE in tail

* Remove timeout for Mac compatibility

* Disable pipeline on Mac

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,5 +1,12 @@
 name: test
-on: [push, pull_request]
+on:
+  push:
+    branches:
+    - master
+  pull_request:
+    branches:
+    - master
+    
 
 jobs:
   test:
@@ -84,6 +91,7 @@ jobs:
         done
 
   quickstart:
+    timeout-minutes: 15
     strategy:
       fail-fast: false
       matrix:
@@ -92,9 +100,6 @@ jobs:
         ocaml:
         - 5.2.x
         - 4.14.x
-        include:
-        - os: macos-latest
-          ocaml: 4.14.x
 
     runs-on: ${{matrix.os}}
     steps:
@@ -108,10 +113,19 @@ jobs:
       run: |
         set -xe
         touch output
-        tail -f output | grep --line-buffered 'Ctrl' | xargs -L1 -I FOO bash -c "echo Success && touch success && killall middleware.exe" &
+        (
+            # tail will receive SIGPIPE once grep finds its match and fail -> catch with || true
+            if (tail -f output || true) | grep -q --line-buffered 'Ctrl'; then
+               echo Success
+               touch success
+            else
+                echo Failed with $?
+            fi
+            killall middleware.exe
+        ) &
         tail -f output &
-        (curl -fsSL https://raw.githubusercontent.com/camlworks/dream/$GITHUB_SHA/example/quickstart.sh | bash -s $GITHUB_SHA) >output 2>&1
-        sleep 1
+        ((curl -fsSL https://raw.githubusercontent.com/camlworks/dream/$GITHUB_SHA/example/quickstart.sh | bash -s $GITHUB_SHA) || true) > output 2>&1
+        bash -c 'while [ ! -f success ]; do sleep 0.1; done'
         if [ -f success ]
         then
           exit 0
